"""Shared design defaults for FDM consumer-product CAD work.

All values are millimeters unless otherwise noted.
"""

from __future__ import annotations

INCH_TO_MM = 25.4

DEFAULT_NOZZLE_DIAMETER_MM = 0.4
DEFAULT_LAYER_HEIGHT_MM = 0.2

DEFAULT_GENERAL_CLEARANCE_MM = 0.30
DEFAULT_SLIDING_CLEARANCE_MM = 0.40
DEFAULT_ROTATING_CLEARANCE_MM = 0.45
DEFAULT_SNAP_CLEARANCE_MM = 0.25
DEFAULT_PRESS_FIT_OFFSET_MM = -0.10
DEFAULT_SCREW_CLEARANCE_MM = 0.20
DEFAULT_INSERT_CLEARANCE_MM = 0.05
DEFAULT_LID_FIT_CLEARANCE_MM = 0.35

DEFAULT_MIN_WALL_MM = 1.6
DEFAULT_STRUCTURAL_WALL_MM = 2.4
DEFAULT_BOSS_WALL_MM = 2.0
DEFAULT_FILLET_MM = 1.0
DEFAULT_CHAMFER_MM = 0.5

# Supplier-dependent starting values — confirm against insert datasheet.
M3_CLEARANCE_HOLE_MM = 3.4
M3_HEAT_SET_INSERT_HOLE_MM = 4.2
M3_HEAD_COUNTERBORE_MM = 6.2
M3_HEAD_COUNTERBORE_DEPTH_MM = 3.2
M3_NUT_FLAT_TO_FLAT_MM = 5.5
M3_NUT_THICKNESS_MM = 2.4

M4_CLEARANCE_HOLE_MM = 4.5
M4_HEAT_SET_INSERT_HOLE_MM = 5.6

EXPORT_TOLERANCE_DRAFT_MM = 0.15
EXPORT_TOLERANCE_NORMAL_MM = 0.05
EXPORT_TOLERANCE_FINE_MM = 0.02

PROJECT_NAME = "startup_cad"
DEFAULT_REVISION = "a"
